# Generated by Django 3.0.8 on 2020-07-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='old dojo', max_length=255),
            preserve_default=False,
        ),
    ]
