# Generated by Django 3.0.8 on 2020-07-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
