# Generated by Django 3.0.8 on 2020-07-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quotes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
